import { Icon } from '@iconify/react';
import { reactIcon, pythonIcon, javascriptIcon, typescriptIcon, mobxIcon,
    mongodbIcon, htmlIcon, cssIcon, bootstrapIcon, javaIcon, cplusIcon,
    cIcon, swiftIcon, googleIcon, pandasIcon, pytorchIcon, firebaseIcon,
    gitIcon, flaskIcon, hfIcon, ApiIcon, TuneIcon, MicIcon, TextFieldsIcon,
    MemoryIcon, CodeIcon }
    from './skillsLogos';
import LibrosaIcon from '../../assets/librosa.png';

const skills = [
    { name: 'Python', icon: <Icon icon={pythonIcon} /> },
    { name: 'React', icon: <Icon icon={reactIcon} /> },
    { name: 'JavaScript', icon: <Icon icon={javascriptIcon} />},
    { name: 'TypeScript', icon: <Icon icon={typescriptIcon} /> },
    { name: 'MobX', icon:<Icon icon={mobxIcon} /> },
    { name: 'MongoDB', icon: <Icon icon={mongodbIcon} /> },
    { name: 'HTML', icon: <Icon icon={htmlIcon} /> },
    { name: 'CSS/SCSS', icon: <Icon icon={cssIcon} /> },
    { name: 'Bootstrap', icon: <Icon icon={bootstrapIcon} /> },
    { name: 'Java', icon: <Icon icon={javaIcon} /> },
    { name: 'C', icon: <Icon icon={cIcon} /> },
    { name: 'C++', icon: <Icon icon={cplusIcon} /> },
    { name: 'Objective-C', icon: <div style={{ fontWeight: 'bold', fontSize: '1.2rem', color: '#007aff' }}>OC</div> },
    { name: 'Swift', icon: <Icon icon={swiftIcon} /> },
    { name: 'SwiftUI', icon: <Icon icon="logos:swift" /> },
    { name: 'Go', icon: <Icon icon="logos:go" /> },
    { name: 'Wireshark', icon: <Icon icon="simple-icons:wireshark" style={{ color: '#1679A7' }} /> },
    { name: 'Flask', icon: <Icon icon="simple-icons:flask" style={{ color: '#7ec8e0' }} /> },
    { name: 'REST APIs', icon: <ApiIcon style={{ fontSize: 20, color: '#007bff' }} /> },
    { name: 'Google APIs', icon: <Icon icon={googleIcon} /> },
    { name: 'Hugging Face Transformers', icon: <Icon icon={hfIcon} />},
    { name: 'Fine-tuning', icon: <TuneIcon style={{ fontSize: 20, color: '#007bff' }} /> },
    { name: 'Librosa', icon: <img src={LibrosaIcon} alt="Librosa" style={{ width: 20, height: 20 }} /> },
    { name: 'Pandas', icon: <Icon icon={pandasIcon} /> },
    { name: 'PyTorch', icon: <Icon icon={pytorchIcon} /> },
    { name: 'Regex', icon: <CodeIcon style={{ fontSize: 20, color: 'white' }} /> },
    { name: 'High Performance Computing', icon: <MemoryIcon style={{ fontSize: 20, color: '#A9A9A9' }} /> },
    { name: 'Firebase', icon: <Icon icon={firebaseIcon} /> },
    { name: 'Speech Recognition', icon: <MicIcon style={{ fontSize: 20, color: 'darkgray' }} /> },
    { name: 'OCR', icon: <TextFieldsIcon style={{ fontSize: 20, color: '#007bff' }} /> },
    { name: 'Git', icon: <Icon icon={gitIcon} /> },
    { name: 'Node.js', icon: <Icon icon="logos:nodejs-icon" /> },
    { name: 'Express.js', icon: <Icon icon="simple-icons:express" style={{ color: 'white' }} /> },
    { name: 'Docker', icon: <Icon icon="logos:docker-icon" /> },
    { name: 'TensorFlow', icon: <Icon icon="logos:tensorflow" /> },
    { name: 'NumPy', icon: <Icon icon="logos:numpy" /> },
    { name: 'Xcode', icon: <Icon icon="logos:xcode" /> },
  ];

  export default skills;