export { default as reactIcon } from '@iconify/icons-logos/react';
export { default as pythonIcon } from '@iconify/icons-logos/python';
export { default as javascriptIcon } from '@iconify/icons-logos/javascript';
export { default as typescriptIcon }from '@iconify/icons-logos/typescript-icon';
export { default as mobxIcon }from '@iconify/icons-logos/mobx';
export { default as htmlIcon }from '@iconify/icons-logos/html-5';
export { default as mongodbIcon }from '@iconify/icons-logos/mongodb-icon';
export { default as cssIcon }from '@iconify/icons-logos/css-3';
export { default as bootstrapIcon }from '@iconify/icons-logos/bootstrap';
export { default as javaIcon }from '@iconify/icons-logos/java';
export { default as cIcon }from '@iconify/icons-logos/c';
export { default as cplusIcon }from '@iconify/icons-logos/c-plusplus';
export { default as swiftIcon }from '@iconify/icons-logos/swift';
export { default as flaskIcon }from '@iconify/icons-logos/flask';
export { default as ApiIcon} from '@mui/icons-material/Api';
export { default as googleIcon } from '@iconify/icons-logos/google-icon';
export { default as hfIcon } from '@iconify/icons-noto-v1/hugging-face';
export { default as GraphicsIcon }from '@mui/icons-material/GraphicEq';
export { default as TuneIcon }from '@mui/icons-material/Tune';
export { default as pandasIcon }from '@iconify/icons-logos/pandas-icon';
export { default as pytorchIcon }from '@iconify/icons-logos/pytorch-icon';
export { default as CodeIcon }from '@mui/icons-material/Code';;
export { default as MemoryIcon }from '@mui/icons-material/Memory';
export { default as firebaseIcon }from '@iconify/icons-logos/firebase';
export { default as MicIcon }from '@mui/icons-material/Mic';
export { default as TextFieldsIcon }from '@mui/icons-material/TextFields';
export { default as gitIcon }from '@iconify/icons-logos/git-icon';